### ISSUE TITLE
Add pages with man pages for the rnp, rnpkeys and librnp.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnpgp.org#28]
As now we have manuals in .adoc format, we should add those to the site as well, so search requests like `rnp generate key` or `rnp encrypt` will land on a friendly-looking page.

**Comment by strogonoff** [comment]
They are supposed to be part of the site, actually! Filed https://github.com/rnpgp/rnpgp.org/issues/33 (this may be closed in favor of that, I presume) and am looking into what’s going wrong on CI.

**Comment by ni4** [comment]
@strogonoff I'm not that familiar with Open Project theme yet, but as I see now at the site, it just picks up `.adoc` files from the `docs` folder. However in this issue I mean inclusion of `src/rnp/rnp.1.adoc`, `src/rnpkeys/rnpkeys.1.adoc` and `src/lib/librnp.3.adoc`.

**Comment by strogonoff** [comment]
Understood. Yes, it doesn’t handle that yet. It’s not terribly complicated to add, but I’m not sure yet whether this should be implemented in an abstract way (after all, it’s just a set of adoc files in another directory than docs/), or support for specifically man page rendering should be added…
