### ISSUE TITLE
Add feedback page to site navigation on the bottom

### ISSUE THREAD

**Issue by strogonoff** [rnpgp/rnpgp.org#31]
The page is here: https://www.rnpgp.org/feedback/

**Comment by strogonoff** [comment]
Added the link: 

<img width="1143" alt="Screenshot 2021-03-19 at 8 05 07 AM" src="https://user-images.githubusercontent.com/292959/111708802-d88dc980-8889-11eb-9891-a3899210afed.png">

**Comment by ronaldtse** [comment]
Thanks @strogonoff !
